print('Algumas n.is')
n = input('Digite palavras ou numeros: ')
print('É um numerico?', n.isnumeric())
print('É alfabeto?', n.isalpha())
print('Contem numeros decimais?', n.isdecimal())
print('Contem algum digito?', n.isdigit())
print('O indentificador e valido no Python?', n.isidentifier())
print('Esta tudo em minusculo?', n.islower())
print('É imprimivel?', n.isprintable())
print('Contem espaço?', n.isspace())
print('a palavras contem primeira letra em maiusculo?', n.istitle())
print('Esta tudo em maiusculo?', n.isupper())
print('É tudo letras?', n.isascii())
